-- Align previously deployed core tables with the fields used by dashboard.js.

ALTER TABLE public.doppio_business_profile
    ADD COLUMN IF NOT EXISTS loyalty_discount_rate numeric NOT NULL DEFAULT 10;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'public.doppio_business_profile'::regclass
          AND attname = 'id'
          AND attidentity <> ''
    ) THEN
        ALTER TABLE public.doppio_business_profile
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
-- Older builds created multiple profile rows for the same tenant. Keep the
-- newest row so tenant-scoped profile upserts can use a unique conflict key.
DELETE FROM public.doppio_business_profile older
USING public.doppio_business_profile newer
WHERE older.tenant_id = newer.tenant_id
  AND older.tenant_id IS NOT NULL
  AND (
      older.updated_at < newer.updated_at
      OR (older.updated_at = newer.updated_at AND older.id < newer.id)
  );
CREATE UNIQUE INDEX IF NOT EXISTS doppio_business_profile_tenant_unique
    ON public.doppio_business_profile (tenant_id);
DO $$
DECLARE
    sequence_name text;
BEGIN
    sequence_name := pg_get_serial_sequence('public.doppio_business_profile', 'id');
    IF sequence_name IS NOT NULL THEN
        PERFORM setval(sequence_name, GREATEST(COALESCE((SELECT max(id) FROM public.doppio_business_profile), 0) + 1, 1), false);
    END IF;
END $$;

DELETE FROM public.doppio_menu older
USING public.doppio_menu newer
WHERE older.tenant_id = newer.tenant_id
  AND lower(older.name) = lower(newer.name)
  AND older.id < newer.id;
ALTER TABLE public.doppio_menu
    ADD CONSTRAINT doppio_menu_tenant_name_unique UNIQUE (tenant_id, name);

ALTER TABLE public.doppio_bills
    ADD COLUMN IF NOT EXISTS "shiftId" text DEFAULT '';

ALTER TABLE public.doppio_inventory
    ADD COLUMN IF NOT EXISTS label text DEFAULT '',
    ADD COLUMN IF NOT EXISTS max_stock numeric NOT NULL DEFAULT 1000,
    ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT 'food';

ALTER TABLE public.doppio_pending_orders
    ADD COLUMN IF NOT EXISTS subtotal numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS discount numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gst numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "paymentMethod" text NOT NULL DEFAULT 'UPI',
    ADD COLUMN IF NOT EXISTS "dateTime" text NOT NULL DEFAULT '';
ALTER TABLE public.doppio_pending_orders
    DROP CONSTRAINT IF EXISTS doppio_pending_orders_status_check;

ALTER TABLE public.doppio_shifts
    ADD COLUMN IF NOT EXISTS "expectedCash" numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "actualCash" numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS variance numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "totalPayouts" numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "totalSafeDrops" numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS notes text DEFAULT '';
ALTER TABLE public.doppio_shifts DROP CONSTRAINT IF EXISTS doppio_shifts_status_check;
UPDATE public.doppio_shifts SET status = upper(status);
ALTER TABLE public.doppio_shifts
    ADD CONSTRAINT doppio_shifts_status_check CHECK (status IN ('OPEN', 'CLOSED'));

ALTER TABLE public.doppio_shift_events
    ADD COLUMN IF NOT EXISTS "eventId" text,
    ADD COLUMN IF NOT EXISTS "eventType" text NOT NULL DEFAULT 'PAYOUT',
    ADD COLUMN IF NOT EXISTS reason text DEFAULT '',
    ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone NOT NULL DEFAULT now();
UPDATE public.doppio_shift_events SET "eventId" = COALESCE("eventId", 'EVENT-' || id::text);
ALTER TABLE public.doppio_shift_events ALTER COLUMN "eventId" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS doppio_shift_events_tenant_event_unique
    ON public.doppio_shift_events (tenant_id, "eventId");

ALTER TABLE public.doppio_employees
    ALTER COLUMN leaves TYPE jsonb USING to_jsonb(leaves);
CREATE UNIQUE INDEX IF NOT EXISTS doppio_employees_tenant_id_unique
    ON public.doppio_employees (tenant_id, id);

ALTER TABLE public.doppio_leave_requests
    ADD COLUMN IF NOT EXISTS type text NOT NULL DEFAULT 'Casual',
    ADD COLUMN IF NOT EXISTS "startDate" date,
    ADD COLUMN IF NOT EXISTS "endDate" date,
    ADD COLUMN IF NOT EXISTS days integer NOT NULL DEFAULT 1;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'doppio_leave_requests' AND column_name = 'fromDate'
    ) THEN
        UPDATE public.doppio_leave_requests
        SET "startDate" = COALESCE("startDate", "fromDate"),
            "endDate" = COALESCE("endDate", "toDate"),
            type = COALESCE(NULLIF(type, ''), "leaveType");
    END IF;
END $$;
ALTER TABLE public.doppio_leave_requests
    ALTER COLUMN "startDate" SET NOT NULL,
    ALTER COLUMN "endDate" SET NOT NULL;

ALTER TABLE public.doppio_attendance
    ADD COLUMN IF NOT EXISTS "clockInTime" text DEFAULT '',
    ADD COLUMN IF NOT EXISTS "clockOutTime" text DEFAULT '',
    ADD COLUMN IF NOT EXISTS "hoursWorked" numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS shift text DEFAULT '',
    ADD COLUMN IF NOT EXISTS wages numeric NOT NULL DEFAULT 0;
ALTER TABLE public.doppio_attendance DROP CONSTRAINT IF EXISTS doppio_attendance_status_check;
CREATE UNIQUE INDEX IF NOT EXISTS doppio_leave_requests_tenant_id_unique
    ON public.doppio_leave_requests (tenant_id, id);
CREATE UNIQUE INDEX IF NOT EXISTS doppio_attendance_tenant_id_unique
    ON public.doppio_attendance (tenant_id, id);

ALTER TABLE public.doppio_crm
    ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT now();

ALTER TABLE public.doppio_inventory_batches
    ALTER COLUMN id TYPE text USING id::text,
    ADD COLUMN IF NOT EXISTS qty numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "expiryDate" date,
    ADD COLUMN IF NOT EXISTS "receivedDate" date;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'doppio_inventory_batches' AND column_name = 'quantity'
    ) THEN
        UPDATE public.doppio_inventory_batches
        SET qty = COALESCE(NULLIF(qty, 0), quantity),
            "expiryDate" = COALESCE("expiryDate", expiry_date);
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS doppio_inventory_batches_tenant_id_unique
    ON public.doppio_inventory_batches (tenant_id, id);
ALTER TABLE public.doppio_inventory_batches DROP CONSTRAINT IF EXISTS doppio_inventory_batches_pkey;
ALTER TABLE public.doppio_inventory_batches
    ADD CONSTRAINT doppio_inventory_batches_pkey PRIMARY KEY (tenant_id, id);

ALTER TABLE public.doppio_notifications
    ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'all',
    ADD COLUMN IF NOT EXISTS timestamp text DEFAULT '',
    ADD COLUMN IF NOT EXISTS "isRead" boolean NOT NULL DEFAULT false;
CREATE UNIQUE INDEX IF NOT EXISTS doppio_notifications_tenant_id_unique
    ON public.doppio_notifications (tenant_id, id);
ALTER TABLE public.doppio_notifications DROP CONSTRAINT IF EXISTS doppio_notifications_pkey;
ALTER TABLE public.doppio_notifications
    ADD CONSTRAINT doppio_notifications_pkey PRIMARY KEY (tenant_id, id);

ALTER TABLE public.doppio_custom_recipes
    ADD COLUMN IF NOT EXISTS ingredients jsonb NOT NULL DEFAULT '{}'::jsonb;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'doppio_custom_recipes' AND column_name = 'recipe'
    ) THEN
        UPDATE public.doppio_custom_recipes
        SET ingredients = recipe
        WHERE ingredients = '{}'::jsonb AND recipe IS NOT NULL;
    END IF;
END $$;

ALTER TABLE public.doppio_inventory_thresholds
    ADD COLUMN IF NOT EXISTS threshold numeric NOT NULL DEFAULT 15,
    ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT now();
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'doppio_inventory_thresholds' AND column_name = 'threshold_pct'
    ) THEN
        UPDATE public.doppio_inventory_thresholds
        SET threshold = threshold_pct
        WHERE threshold = 15 AND threshold_pct IS NOT NULL;
    END IF;
END $$;

ALTER TABLE public.doppio_pos_popularity
    ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT now();

ALTER TABLE public.doppio_draft_orders
    ADD COLUMN IF NOT EXISTS "draftName" text DEFAULT '',
    ADD COLUMN IF NOT EXISTS "customerName" text DEFAULT '',
    ADD COLUMN IF NOT EXISTS "customerPhone" text DEFAULT '',
    ADD COLUMN IF NOT EXISTS "paymentMethod" text DEFAULT 'UPI',
    ADD COLUMN IF NOT EXISTS subtotal numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gst numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone NOT NULL DEFAULT now();
ALTER TABLE public.doppio_draft_orders
    DROP CONSTRAINT IF EXISTS "doppio_draft_orders_draftId_key";
CREATE UNIQUE INDEX IF NOT EXISTS doppio_draft_orders_tenant_draft_unique
    ON public.doppio_draft_orders (tenant_id, "draftId");

ALTER TABLE public.doppio_employees DROP CONSTRAINT IF EXISTS doppio_employees_pkey;
ALTER TABLE public.doppio_employees
    ADD CONSTRAINT doppio_employees_pkey PRIMARY KEY (tenant_id, id);
