-- ============================================================
-- Core POS Operational Tables
-- Must be run BEFORE supabase_migration.sql / auth_hardening.
-- These tables are the operational heart of every tenant workspace.
-- ============================================================

-- Business Profile (one row per tenant)
CREATE TABLE IF NOT EXISTS public.doppio_business_profile (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    business_name   text NOT NULL DEFAULT 'My Restaurant',
    address         text NOT NULL DEFAULT '',
    phone           text NOT NULL DEFAULT '',
    gst_enabled     boolean NOT NULL DEFAULT false,
    gst_rate        numeric NOT NULL DEFAULT 18.00,
    gst_number      text DEFAULT '',
    upi_vpa         text DEFAULT '',
    loyalty_discount_enabled boolean NOT NULL DEFAULT false,
    loyalty_discount_rate numeric NOT NULL DEFAULT 10,
    passcode_lock_enabled boolean NOT NULL DEFAULT false,
    passcode         text DEFAULT '',
    crm_enabled      boolean NOT NULL DEFAULT true,
    tax_enabled      boolean NOT NULL DEFAULT true,
    sound_enabled    boolean NOT NULL DEFAULT false,
    whatsapp_enabled boolean NOT NULL DEFAULT false,
    whatsapp_gateway_enabled boolean NOT NULL DEFAULT false,
    whatsapp_gateway_url text DEFAULT '',
    whatsapp_gateway_token text DEFAULT '',
    shift_enabled    boolean NOT NULL DEFAULT false,
    shift_default_float numeric NOT NULL DEFAULT 2000,
    shift_max_drawer    numeric NOT NULL DEFAULT 5000,
    shift_pos_lock      boolean NOT NULL DEFAULT true,
    feature_flags   jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamp with time zone NOT NULL DEFAULT now(),
    updated_at      timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id)
);

CREATE INDEX IF NOT EXISTS doppio_business_profile_tenant_idx
    ON public.doppio_business_profile (tenant_id);

-- Menu Items
CREATE TABLE IF NOT EXISTS public.doppio_menu (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    name        text NOT NULL,
    description text DEFAULT '',
    price       numeric NOT NULL DEFAULT 0,
    category    text NOT NULL DEFAULT 'Other',
    icon        text DEFAULT '☕',
    bestseller  boolean NOT NULL DEFAULT false,
    available   boolean NOT NULL DEFAULT true,
    prep_time   integer DEFAULT 5,
    recipe_specs jsonb DEFAULT '{}'::jsonb,
    created_at  timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);

CREATE INDEX IF NOT EXISTS doppio_menu_tenant_idx
    ON public.doppio_menu (tenant_id);

-- Inventory Stock Levels (key-value, one row per ingredient per tenant)
CREATE TABLE IF NOT EXISTS public.doppio_inventory (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    key         text NOT NULL,
    current     numeric NOT NULL DEFAULT 0,
    unit        text NOT NULL DEFAULT 'ml',
    updated_at  timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, key)
);

CREATE INDEX IF NOT EXISTS doppio_inventory_tenant_idx
    ON public.doppio_inventory (tenant_id);

-- Bills / Sales Invoices
CREATE TABLE IF NOT EXISTS public.doppio_bills (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    "orderId"       text NOT NULL,
    "customerName"  text DEFAULT 'Walk-in',
    "customerPhone" text DEFAULT '',
    items           jsonb NOT NULL DEFAULT '[]'::jsonb,
    subtotal        numeric NOT NULL DEFAULT 0,
    gst             numeric NOT NULL DEFAULT 0,
    discount        numeric NOT NULL DEFAULT 0,
    total           numeric NOT NULL DEFAULT 0,
    "paymentMethod" text NOT NULL DEFAULT 'Cash',
    "orderType"     text NOT NULL DEFAULT 'Takeaway',
    "tableNumber"   text DEFAULT '',
    "shiftId"       text DEFAULT '',
    "dateTime"      text NOT NULL DEFAULT '',
    created_at      timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, "orderId")
);

CREATE INDEX IF NOT EXISTS idx_doppio_bills_order_id ON public.doppio_bills ("orderId");
CREATE INDEX IF NOT EXISTS idx_doppio_bills_date ON public.doppio_bills ("dateTime");
CREATE INDEX IF NOT EXISTS idx_doppio_bills_tenant_date ON public.doppio_bills (tenant_id, created_at DESC);

-- QR / Online Pending Orders (KDS feed)
CREATE TABLE IF NOT EXISTS public.doppio_pending_orders (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    "orderId"       text NOT NULL,
    "customerName"  text DEFAULT '',
    "customerPhone" text DEFAULT '',
    items           jsonb NOT NULL DEFAULT '[]'::jsonb,
    total           numeric NOT NULL DEFAULT 0,
    subtotal        numeric NOT NULL DEFAULT 0,
    discount        numeric NOT NULL DEFAULT 0,
    gst             numeric NOT NULL DEFAULT 0,
    "paymentMethod" text NOT NULL DEFAULT 'UPI',
    "orderType"     text NOT NULL DEFAULT 'QR',
    "tableNumber"   text DEFAULT '',
    "dateTime"      text NOT NULL DEFAULT '',
    status          text NOT NULL DEFAULT 'Pending Review',
    created_at      timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, "orderId")
);

CREATE INDEX IF NOT EXISTS idx_doppio_pending_orders_tenant_status ON public.doppio_pending_orders (tenant_id, status, created_at DESC);

-- Cashier Shifts
CREATE TABLE IF NOT EXISTS public.doppio_shifts (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    "shiftId"       text NOT NULL,
    "cashierName"   text NOT NULL DEFAULT '',
    "openingFloat"  numeric NOT NULL DEFAULT 0,
    "closingFloat"  numeric DEFAULT NULL,
    "totalSalesCash" numeric NOT NULL DEFAULT 0,
    "totalSalesUpi"  numeric NOT NULL DEFAULT 0,
    "totalSalesCard" numeric NOT NULL DEFAULT 0,
    "expectedCash"  numeric NOT NULL DEFAULT 0,
    "actualCash"    numeric NOT NULL DEFAULT 0,
    variance        numeric NOT NULL DEFAULT 0,
    "totalPayouts"  numeric NOT NULL DEFAULT 0,
    "totalSafeDrops" numeric NOT NULL DEFAULT 0,
    "openedAt"      text NOT NULL DEFAULT '',
    "closedAt"      text DEFAULT '',
    status          text NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED')),
    notes           text DEFAULT '',
    created_at      timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, "shiftId")
);

CREATE INDEX IF NOT EXISTS idx_doppio_shifts_id ON public.doppio_shifts ("shiftId");
CREATE INDEX IF NOT EXISTS idx_doppio_shifts_tenant_status ON public.doppio_shifts (tenant_id, status);

-- Shift Events (drawer drops, payouts)
CREATE TABLE IF NOT EXISTS public.doppio_shift_events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    "eventId"   text NOT NULL,
    "shiftId"   text NOT NULL,
    "eventType" text NOT NULL DEFAULT 'PAYOUT',
    amount      numeric NOT NULL DEFAULT 0,
    reason      text DEFAULT '',
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, "eventId")
);

CREATE INDEX IF NOT EXISTS idx_doppio_shift_events_shift ON public.doppio_shift_events ("shiftId");
CREATE INDEX IF NOT EXISTS idx_doppio_shift_events_tenant ON public.doppio_shift_events (tenant_id);

-- Employees / HR
CREATE TABLE IF NOT EXISTS public.doppio_employees (
    id          text NOT NULL,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    name        text NOT NULL,
    role        text NOT NULL DEFAULT 'staff',
    contact     text DEFAULT '',
    "baseSalary" numeric NOT NULL DEFAULT 0,
    shift       text NOT NULL DEFAULT 'Morning',
    leaves      jsonb NOT NULL DEFAULT '{}'::jsonb,
    status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at  timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id)
);

CREATE INDEX IF NOT EXISTS doppio_employees_tenant_idx ON public.doppio_employees (tenant_id);

-- Leave Requests
CREATE TABLE IF NOT EXISTS public.doppio_leave_requests (
    id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    "employeeId" text NOT NULL,
    "employeeName" text NOT NULL,
    type        text NOT NULL DEFAULT 'Casual',
    "startDate" date NOT NULL,
    "endDate"   date NOT NULL,
    reason      text DEFAULT '',
    status      text NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    days        integer NOT NULL DEFAULT 1,
    created_at  timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS doppio_leave_requests_tenant_idx ON public.doppio_leave_requests (tenant_id);

-- Attendance
CREATE TABLE IF NOT EXISTS public.doppio_attendance (
    id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    "employeeId" text NOT NULL,
    "employeeName" text NOT NULL,
    date        date NOT NULL,
    status      text NOT NULL DEFAULT 'Active',
    "clockInTime" text DEFAULT '',
    "clockOutTime" text DEFAULT '',
    "hoursWorked" numeric NOT NULL DEFAULT 0,
    shift       text DEFAULT '',
    wages       numeric NOT NULL DEFAULT 0,
    created_at  timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS doppio_attendance_tenant_idx ON public.doppio_attendance (tenant_id);

-- CRM / Customer Loyalty Ledger
CREATE TABLE IF NOT EXISTS public.doppio_crm (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    phone       text NOT NULL,
    name        text DEFAULT 'Guest',
    visits      integer NOT NULL DEFAULT 0,
    total_spend numeric NOT NULL DEFAULT 0,
    last_visit  text DEFAULT '',
    loyalty_points integer NOT NULL DEFAULT 0,
    notes       text DEFAULT '',
    created_at  timestamp with time zone NOT NULL DEFAULT now(),
    updated_at  timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, phone)
);

CREATE INDEX IF NOT EXISTS doppio_crm_tenant_idx ON public.doppio_crm (tenant_id);

-- Inventory Batches (FEFO expiry tracking)
CREATE TABLE IF NOT EXISTS public.doppio_inventory_batches (
    id          text NOT NULL,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    ingredient_key text NOT NULL,
    qty         numeric NOT NULL DEFAULT 0,
    "expiryDate" date,
    "receivedDate" date,
    created_at  timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id)
);

CREATE INDEX IF NOT EXISTS doppio_inventory_batches_tenant_idx ON public.doppio_inventory_batches (tenant_id);

-- Notifications / Alerts
CREATE TABLE IF NOT EXISTS public.doppio_notifications (
    id          text NOT NULL,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    title       text NOT NULL,
    message     text NOT NULL,
    type        text NOT NULL DEFAULT 'info',
    role        text NOT NULL DEFAULT 'all',
    timestamp   text DEFAULT '',
    "isRead"    boolean NOT NULL DEFAULT false,
    created_at  timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id)
);

CREATE INDEX IF NOT EXISTS doppio_notifications_tenant_idx ON public.doppio_notifications (tenant_id, "isRead", created_at DESC);

-- Custom Recipes (overrides for the standard recipe DB)
CREATE TABLE IF NOT EXISTS public.doppio_custom_recipes (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    item_name   text NOT NULL,
    ingredients jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at  timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, item_name)
);

CREATE INDEX IF NOT EXISTS doppio_custom_recipes_tenant_idx ON public.doppio_custom_recipes (tenant_id);

-- Inventory Low-Stock Thresholds (per ingredient, per tenant)
CREATE TABLE IF NOT EXISTS public.doppio_inventory_thresholds (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    ingredient_key  text NOT NULL,
    threshold       numeric NOT NULL DEFAULT 15,
    updated_at      timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, ingredient_key)
);

CREATE INDEX IF NOT EXISTS doppio_inventory_thresholds_tenant_idx ON public.doppio_inventory_thresholds (tenant_id);

-- POS Item Popularity Counters
CREATE TABLE IF NOT EXISTS public.doppio_pos_popularity (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    item_name   text NOT NULL,
    count       integer NOT NULL DEFAULT 0,
    updated_at  timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, item_name)
);

CREATE INDEX IF NOT EXISTS doppio_pos_popularity_tenant_idx ON public.doppio_pos_popularity (tenant_id);

-- Draft / Held Orders (active cart snapshots)
CREATE TABLE IF NOT EXISTS public.doppio_draft_orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   uuid REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    "draftId"   text NOT NULL,
    "draftName" text DEFAULT '',
    "customerName" text DEFAULT '',
    "customerPhone" text DEFAULT '',
    "paymentMethod" text DEFAULT 'UPI',
    items       jsonb NOT NULL DEFAULT '[]'::jsonb,
    subtotal    numeric NOT NULL DEFAULT 0,
    gst         numeric NOT NULL DEFAULT 0,
    total       numeric NOT NULL DEFAULT 0,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, "draftId")
);

CREATE INDEX IF NOT EXISTS idx_doppio_drafts_id ON public.doppio_draft_orders ("draftId");
CREATE INDEX IF NOT EXISTS idx_doppio_drafts_tenant ON public.doppio_draft_orders (tenant_id);

-- ============================================================
-- Enable RLS on all core tables
-- (tenant-data edge function uses service_role to bypass RLS)
-- ============================================================
DO $$
DECLARE
    t text;
    core_tables text[] := ARRAY[
        'doppio_business_profile', 'doppio_menu', 'doppio_inventory',
        'doppio_bills', 'doppio_pending_orders', 'doppio_shifts',
        'doppio_shift_events', 'doppio_employees', 'doppio_leave_requests',
        'doppio_attendance', 'doppio_crm', 'doppio_inventory_batches',
        'doppio_notifications', 'doppio_custom_recipes',
        'doppio_inventory_thresholds', 'doppio_pos_popularity',
        'doppio_draft_orders'
    ];
BEGIN
    FOREACH t IN ARRAY core_tables LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated', t);
    END LOOP;
END $$;
