-- ============================================================
-- Wave 2: industry-grade bill numbers + atomic inventory deduct
--
-- 1) Per-tenant daily bill sequence (multi-device safe)
-- 2) Guarantee UNIQUE (tenant_id, order_id) on doppio_bills
-- 3) Idempotent inventory deduction RPC keyed by bill_key
-- ============================================================

-- ---- Bill sequences -------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.doppio_bill_sequences (
    tenant_id   uuid NOT NULL REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    day_key     text NOT NULL,          -- YYMMDD in outlet intent (IST default)
    last_seq    integer NOT NULL DEFAULT 0,
    updated_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, day_key)
);

CREATE INDEX IF NOT EXISTS doppio_bill_sequences_tenant_idx
    ON public.doppio_bill_sequences (tenant_id);

-- Ensure bills unique on (tenant_id, order_id) whether camelCase or snake_case
DO $$
BEGIN
  -- Snake case path (post 20260707160000)
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'doppio_bills' AND column_name = 'order_id'
  ) THEN
    -- Drop legacy camelCase unique if present
    ALTER TABLE public.doppio_bills DROP CONSTRAINT IF EXISTS doppio_bills_tenant_order_id_key;
    ALTER TABLE public.doppio_bills DROP CONSTRAINT IF EXISTS "doppio_bills_orderId_key";
    DROP INDEX IF EXISTS idx_doppio_bills_tenant_order_id;
    DROP INDEX IF EXISTS idx_doppio_bills_order_id;

    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conrelid = 'public.doppio_bills'::regclass
        AND conname = 'doppio_bills_tenant_order_id_uidx'
    ) THEN
      -- Clean duplicates keeping newest id
      DELETE FROM public.doppio_bills older
      USING public.doppio_bills newer
      WHERE older.tenant_id IS NOT NULL
        AND older.tenant_id = newer.tenant_id
        AND older.order_id = newer.order_id
        AND older.id < newer.id;

      ALTER TABLE public.doppio_bills
        ADD CONSTRAINT doppio_bills_tenant_order_id_uidx UNIQUE (tenant_id, order_id);
    END IF;

    CREATE INDEX IF NOT EXISTS idx_doppio_bills_tenant_order_id_sn
      ON public.doppio_bills (tenant_id, order_id);

  ELSIF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'doppio_bills' AND column_name = 'orderId'
  ) THEN
    ALTER TABLE public.doppio_bills DROP CONSTRAINT IF EXISTS "doppio_bills_orderId_key";
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conrelid = 'public.doppio_bills'::regclass
        AND conname = 'doppio_bills_tenant_order_id_key'
    ) THEN
      DELETE FROM public.doppio_bills older
      USING public.doppio_bills newer
      WHERE older.tenant_id IS NOT NULL
        AND older.tenant_id = newer.tenant_id
        AND older."orderId" = newer."orderId"
        AND older.id < newer.id;
      ALTER TABLE public.doppio_bills
        ADD CONSTRAINT doppio_bills_tenant_order_id_key UNIQUE (tenant_id, "orderId");
    END IF;
  END IF;
END $$;

-- Optional idempotency column (not required for unique order_id path)
ALTER TABLE public.doppio_bills
  ADD COLUMN IF NOT EXISTS idempotency_key text;

CREATE UNIQUE INDEX IF NOT EXISTS doppio_bills_tenant_idempotency_uidx
  ON public.doppio_bills (tenant_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL AND idempotency_key <> '';

-- ---- Inventory deduction ledger (idempotency) -----------------------------
CREATE TABLE IF NOT EXISTS public.doppio_inventory_deductions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   uuid NOT NULL REFERENCES public.saas_tenants(id) ON DELETE CASCADE,
    bill_key    text NOT NULL,
    order_id    text DEFAULT '',
    lines       jsonb NOT NULL DEFAULT '[]'::jsonb,
    results     jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, bill_key)
);

CREATE INDEX IF NOT EXISTS doppio_inventory_deductions_tenant_idx
  ON public.doppio_inventory_deductions (tenant_id);

-- ---- RPC: next bill number ------------------------------------------------
CREATE OR REPLACE FUNCTION public.rs_next_bill_no(
  p_tenant_id uuid,
  p_day text DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_day text;
  v_seq integer;
BEGIN
  IF p_tenant_id IS NULL THEN
    RAISE EXCEPTION 'tenant_id required';
  END IF;
  -- Default day key: Asia/Kolkata calendar day as YYMMDD (matches client nextBillNo)
  v_day := COALESCE(
    NULLIF(trim(p_day), ''),
    to_char((timezone('Asia/Kolkata', now())), 'YYMMDD')
  );

  INSERT INTO public.doppio_bill_sequences AS s (tenant_id, day_key, last_seq, updated_at)
  VALUES (p_tenant_id, v_day, 1, now())
  ON CONFLICT (tenant_id, day_key)
  DO UPDATE SET
    last_seq = s.last_seq + 1,
    updated_at = now()
  RETURNING last_seq INTO v_seq;

  RETURN 'RS-' || v_day || '-' || lpad(v_seq::text, 3, '0');
END;
$$;

REVOKE ALL ON FUNCTION public.rs_next_bill_no(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rs_next_bill_no(uuid, text) TO service_role;

-- ---- RPC: atomic inventory deduct (idempotent by bill_key) ----------------
-- p_lines: [{"key":"tomato","name":"Tomato","qty":2.5}, ...]
CREATE OR REPLACE FUNCTION public.rs_deduct_inventory(
  p_tenant_id uuid,
  p_bill_key text,
  p_lines jsonb,
  p_order_id text DEFAULT ''
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing jsonb;
  v_line jsonb;
  v_key text;
  v_name text;
  v_qty numeric;
  v_row public.doppio_inventory%ROWTYPE;
  v_new_stock numeric;
  v_results jsonb := '[]'::jsonb;
  v_deducted int := 0;
  v_missing text[] := ARRAY[]::text[];
  v_low text[] := ARRAY[]::text[];
BEGIN
  IF p_tenant_id IS NULL OR COALESCE(trim(p_bill_key), '') = '' THEN
    RAISE EXCEPTION 'tenant_id and bill_key required';
  END IF;

  -- Already applied? return stored results (idempotent)
  SELECT results INTO v_existing
  FROM public.doppio_inventory_deductions
  WHERE tenant_id = p_tenant_id AND bill_key = p_bill_key;
  IF FOUND THEN
    RETURN jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'results', COALESCE(v_existing, '[]'::jsonb)
    );
  END IF;

  IF p_lines IS NULL OR jsonb_typeof(p_lines) <> 'array' THEN
    p_lines := '[]'::jsonb;
  END IF;

  FOR v_line IN SELECT * FROM jsonb_array_elements(p_lines)
  LOOP
    v_key := lower(trim(COALESCE(v_line->>'key', '')));
    v_name := trim(COALESCE(v_line->>'name', ''));
    v_qty := COALESCE((v_line->>'qty')::numeric, 0);
    IF v_qty <= 0 THEN
      CONTINUE;
    END IF;

    -- Clear previous row; FOUND is checked after each SELECT
    SELECT * INTO v_row FROM public.doppio_inventory WHERE false;

    IF v_key <> '' THEN
      SELECT * INTO v_row
      FROM public.doppio_inventory
      WHERE tenant_id = p_tenant_id AND lower(key) = v_key
      ORDER BY id
      LIMIT 1
      FOR UPDATE;
    END IF;

    IF NOT FOUND AND v_name <> '' THEN
      SELECT * INTO v_row
      FROM public.doppio_inventory
      WHERE tenant_id = p_tenant_id
        AND (
          lower(COALESCE(label, '')) = lower(v_name)
          OR lower(COALESCE(name, '')) = lower(v_name)
          OR lower(COALESCE(key, '')) = lower(regexp_replace(v_name, '[^a-zA-Z0-9]+', '_', 'g'))
        )
      ORDER BY id
      LIMIT 1
      FOR UPDATE;
    END IF;

    IF NOT FOUND OR v_row.id IS NULL THEN
      v_missing := array_append(v_missing, COALESCE(NULLIF(v_name, ''), v_key, '?'));
      v_results := v_results || jsonb_build_array(jsonb_build_object(
        'key', v_key, 'name', v_name, 'qty', v_qty, 'status', 'missing'
      ));
      CONTINUE;
    END IF;

    v_new_stock := GREATEST(0, COALESCE(v_row.current, 0) - v_qty);
    UPDATE public.doppio_inventory
    SET current = v_new_stock,
        updated_at = now()
    WHERE id = v_row.id AND tenant_id = p_tenant_id;

    v_deducted := v_deducted + 1;
    IF COALESCE(v_row.threshold, 0) > 0 AND v_new_stock <= v_row.threshold THEN
      v_low := array_append(v_low, COALESCE(NULLIF(v_row.label, ''), NULLIF(v_row.name, ''), v_row.key));
    END IF;

    v_results := v_results || jsonb_build_array(jsonb_build_object(
      'id', v_row.id,
      'key', v_row.key,
      'name', COALESCE(NULLIF(v_row.label, ''), NULLIF(v_row.name, ''), v_row.key),
      'qty', v_qty,
      'stock_after', v_new_stock,
      'status', 'ok'
    ));
  END LOOP;

  INSERT INTO public.doppio_inventory_deductions (tenant_id, bill_key, order_id, lines, results)
  VALUES (p_tenant_id, p_bill_key, COALESCE(p_order_id, ''), p_lines, v_results);

  RETURN jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'deducted', v_deducted,
    'missing', to_jsonb(v_missing),
    'low_stock', to_jsonb(v_low),
    'results', v_results
  );
END;
$$;

REVOKE ALL ON FUNCTION public.rs_deduct_inventory(uuid, text, jsonb, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rs_deduct_inventory(uuid, text, jsonb, text) TO service_role;

-- Inventory may have optional name column from older builds
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'doppio_inventory' AND column_name = 'name'
  ) THEN
    ALTER TABLE public.doppio_inventory ADD COLUMN name text DEFAULT '';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'doppio_inventory' AND column_name = 'threshold'
  ) THEN
    -- older schema used threshold; some use min via client map only
    ALTER TABLE public.doppio_inventory ADD COLUMN IF NOT EXISTS threshold numeric DEFAULT 0;
  END IF;
END $$;

-- RLS: sequences/deductions only via service role edge (no client policies)
ALTER TABLE public.doppio_bill_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doppio_inventory_deductions ENABLE ROW LEVEL SECURITY;
